[build]
  base = "/"
  publish = "/build/"
  command = "yarn build"
[build.environment]
  NODE_VERSION = "10.13.0"
  YARN_VERSION = "1.17.3"
  NPM_VERSION = "6.4.1"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
